### ISSUE TITLE
Add categories, tags, difficulty

### ISSUE THREAD

**Issue by moeenio** [csourcesc/posts#5]
https://github.com/csourcesc/csourcesc.github.io/pull/25 added support for showing articles categories, tags, and difficulty, as well as related archive pages, and author pages.

Now we should add some categories, tags and difficulty to posts, and add author pages.
Author pages should be in a `authors` directory, and have this front matter :
```
---
name: TheAuthorsName
scratch_url: https://scratch.mit.edu/users/TheAuthorsName
---
```

**Comment by ghost** [comment]
So we have to do this for the two posts that are published already?

**Comment by moeenio** [comment]
Basically yes

**Comment by ghost** [comment]
Okay!

- [ ] Gravity article
- [ ] Smooth animations article

**Comment by ghost** [comment]
@locness3 How do I add thins in existing posts?

**Comment by moeenio** [comment]
Add these to the front matter!

```
---
// Whatever the post already has
categories:
  - category1
  - category2
tags:
  - tag1
  - tag2
difficulty: Easy
---
```
Refer to the Jekyll docs ;)
What do we use as difficulty levels? I would do Novice, Easy, Intermediate, Advanced but if you have other ideas...

**Comment by ghost** [comment]
Maybe we can remove Novice? 3 levels are enough..?

**Comment by moeenio** [comment]
maybe

**Comment by ghost** [comment]
Oh come on just answer with yes or no

**Comment by moeenio** [comment]
I'd keep Novice as a level for pretty much complete beginners.

**Comment by ghost** [comment]
Okay np

**Comment by moeenio** [comment]
half fixed

**Comment by moeenio** [comment]
Added in https://github.com/csourcesc/posts/commit/ce8dfa2ee0aceb80f00046a08662ff5c28bab2c8 https://github.com/csourcesc/posts/commit/c7b7dc5d2949a7ed0f81f045bea4d9115e73df9. If all is okay, last thing is to sync the main repository.

**Comment by moeenio** [comment]
didn't add author pages but

**Comment by moeenio** [comment]
yeah ill just do it
